version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.11.1

    

    steps:
      - checkout
      - run: npm install    
      - run: npm build
      - run: npm test:coverage
          